using System.ComponentModel;

public enum ePartsResources
{
	[Description("Prefabs/Parts/Bedroll_01")]
	Bedroll_01,
	[Description("Prefabs/Parts/Bag/Bag_Lvl1")]
	Bag_Lvl1,
	[Description("Prefabs/Parts/Bag/Bag_Lvl2")]
	Bag_Lvl2,
	[Description("Prefabs/Parts/Bag/Bag_Lvl3")]
	Bag_Lvl3,
	[Description("Prefabs/Parts/Beard/Beard_02")]
	Beard_02,
	[Description("Prefabs/Parts/Beard/Beard_03")]
	Beard_03,
	[Description("Prefabs/Parts/Beard/Beard_04")]
	Beard_04,
	[Description("Prefabs/Parts/Beard/Beard_05")]
	Beard_05,
	[Description("Prefabs/Parts/Beard/Beard_06")]
	Beard_06,
	[Description("Prefabs/Parts/Beard/Beard_07")]
	Beard_07,
	[Description("Prefabs/Parts/FaceAcc/Eyepatch_01")]
	Eyepatch_01,
	[Description("Prefabs/Parts/FaceAcc/GasMask_01")]
	GasMask_01,
	[Description("Prefabs/Parts/FaceAcc/Glasses_01")]
	Glasses_01,
	[Description("Prefabs/Parts/Facemask/Facemask_01")]
	Facemask_01,
	[Description("Prefabs/Parts/Facemask/Facemask_02")]
	Facemask_02,
	[Description("Prefabs/Parts/Facemask/Facemask_03")]
	Facemask_03,
	[Description("Prefabs/Parts/Hat/Earmuffs_01")]
	Earmuffs_01,
	[Description("Prefabs/Parts/Hat/Hat_Bandana_01")]
	Hat_Bandana_01,
	[Description("Prefabs/Parts/Hat/Hat_Beanie_01")]
	Hat_Beanie_01,
	[Description("Prefabs/Parts/Hat/Hat_Beer_01")]
	Hat_Beer_01,
	[Description("Prefabs/Parts/Hat/Hat_Bunny_01")]
	Hat_Bunny_01,
	[Description("Prefabs/Parts/Hat/Hat_Captian_01")]
	Hat_Captian_01,
	[Description("Prefabs/Parts/Hat/Hat_Cap_01")]
	Hat_Cap_01,
	[Description("Prefabs/Parts/Hat/Hat_Cowboy_01")]
	Hat_Cowboy_01,
	[Description("Prefabs/Parts/Hat/Hat_Crown_01")]
	Hat_Crown_01,
	[Description("Prefabs/Parts/Hat/Hat_Cupcake_01")]
	Hat_Cupcake_01,
	[Description("Prefabs/Parts/Hat/Hat_Elf_01")]
	Hat_Elf_01,
	[Description("Prefabs/Parts/Hat/Hat_Fez_01")]
	Hat_Fez_01,
	[Description("Prefabs/Parts/Hat/Hat_FlatTop_01")]
	Hat_FlatTop_01,
	[Description("Prefabs/Parts/Hat/Hat_FlatTop_02")]
	Hat_FlatTop_02,
	[Description("Prefabs/Parts/Hat/Hat_IceCream_01")]
	Hat_IceCream_01,
	[Description("Prefabs/Parts/Hat/Hat_Irish_01")]
	Hat_Irish_01,
	[Description("Prefabs/Parts/Hat/Hat_Knight_01")]
	Hat_Knight_01,
	[Description("Prefabs/Parts/Hat/Hat_Mexican_01")]
	Hat_Mexican_01,
	[Description("Prefabs/Parts/Hat/Hat_Mil_01")]
	Hat_Mil_01,
	[Description("Prefabs/Parts/Hat/Hat_Party_01")]
	Hat_Party_01,
	[Description("Prefabs/Parts/Hat/Hat_Pot_01")]
	Hat_Pot_01,
	[Description("Prefabs/Parts/Hat/Hat_Racoon_01")]
	Hat_Racoon_01,
	[Description("Prefabs/Parts/Hat/Hat_Roadcone_01")]
	Hat_Roadcone_01,
	[Description("Prefabs/Parts/Hat/Hat_Roman_01")]
	Hat_Roman_01,
	[Description("Prefabs/Parts/Hat/Hat_Samurai_01")]
	Hat_Samurai_01,
	[Description("Prefabs/Parts/Hat/Hat_Shark_01")]
	Hat_Shark_01,
	[Description("Prefabs/Parts/Hat/Hat_Squid_01")]
	Hat_Squid_01,
	[Description("Prefabs/Parts/Hat/Hat_Tacticle_01")]
	Hat_Tacticle_01,
	[Description("Prefabs/Parts/Hat/Hat_Turban_01")]
	Hat_Turban_01,
	[Description("Prefabs/Parts/Hat/Hat_Unicorn_01")]
	Hat_Unicorn_01,
	[Description("Prefabs/Parts/Hat/Helmet_01")]
	Helmet_01,
	[Description("Prefabs/Parts/Hat/Helmet_02")]
	Helmet_02,
	[Description("Prefabs/Parts/Hat/Helmet_03")]
	Helmet_03,
	[Description("Prefabs/Parts/Patch/Ammo_01")]
	Ammo_01,
	[Description("Prefabs/Parts/Patch/Patch_Flag_01")]
	Patch_Flag_01,
	[Description("Prefabs/Parts/Patch/Patch_Leaf_01")]
	Patch_Leaf_01,
	[Description("Prefabs/Parts/Patch/Patch_Medic_01")]
	Patch_Medic_01,
	[Description("Prefabs/Parts/Patch/Patch_Medic_02")]
	Patch_Medic_02,
	[Description("Prefabs/Parts/Patch/Patch_Rank_01")]
	Patch_Rank_01,
	[Description("Prefabs/Parts/Patch/Patch_Rank_02")]
	Patch_Rank_02,
	[Description("Prefabs/Parts/Patch/Patch_Rank_03")]
	Patch_Rank_03,
	[Description("Prefabs/Parts/Patch/Patch_Star_01")]
	Patch_Star_01,
	[Description("Prefabs/Parts/Patch/Patch_Star_02")]
	Patch_Star_02,
	[Description("Prefabs/Parts/Pouch/Pouch_01")]
	Pouch_01,
	[Description("Prefabs/Parts/Pouch/Pouch_02")]
	Pouch_02,
	[Description("Prefabs/Parts/Pouch/Pouch_03")]
	Pouch_03,
	[Description("Prefabs/Parts/Pouch/Pouch_04")]
	Pouch_04,
	[Description("Prefabs/Parts/Pouch/Pouch_05")]
	Pouch_05,
	[Description("Prefabs/Parts/Pouch/Pouch_06")]
	Pouch_06,
	[Description("Prefabs/Parts/Pouch/Pouch_07")]
	Pouch_07,
	[Description("Prefabs/Parts/Pouch/Pouch_08")]
	Pouch_08,
	[Description("Prefabs/Parts/Scarf/Scarf_01")]
	Scarf_01,
	[Description("Prefabs/Parts/Scarf/Scarf_02")]
	Scarf_02,
	[Description("Prefabs/Parts/Hair/Female/Female_01")]
	Female_01,
	[Description("Prefabs/Parts/Hair/Female/Female_02")]
	Female_02,
	[Description("Prefabs/Parts/Hair/Female/Female_Default_Hair_01")]
	Female_Default_Hair_01,
	[Description("Prefabs/Parts/Hair/Female/Female_Hair_01")]
	Female_Hair_01,
	[Description("Prefabs/Parts/Hair/Female/Female_Hair_Pigtails_01")]
	Female_Hair_Pigtails_01,
	[Description("Prefabs/Parts/Hair/Male/Male_Default_Hair_01")]
	Male_Default_Hair_01,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_01")]
	Male_Hair_01,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_02")]
	Male_Hair_02,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_03")]
	Male_Hair_03,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_04")]
	Male_Hair_04,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_05")]
	Male_Hair_05,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_06")]
	Male_Hair_06,
	[Description("Prefabs/Parts/Hair/Male/Male_Hair_07")]
	Male_Hair_07,
}
